#!/bin/bash

docker run \
      -it \
      --init \
      -e OPTIMIZELY_TOKEN \
      -e LOCAL_USER_ID=$(id -u) \
      -v $PWD:/src \
      mulby/py-opt-cli:snapshot \
      /usr/local/bin/py-opt-cli "$@"
